# What is Data Cleaning?

Data cleaning is the process of preparing raw data by detecting and correcting errors so it can be effectively used for analysis. It is a foundational step in data preprocessing that ensures datasets are suitable for analytical, statistical and machine learning tasks.

Eliminates duplicates, missing values and inconsistencies that can distort analysis
Enables organizations to make decisions based on accurate and up to date information
Reduces effort and time spent handling errors during data analysis and reporting
Strengthens the reliability of analytics, AI and machine learning outcomes
Supports adherence to data quality standards and regulatory requirements
data_cleaning_process.webp

In [188]:
import pandas as pd

df1 = pd.DataFrame({
    "name": ["mary","John", "mary", 'Jane',"bob", "Alice","John","mary", pd.NA],
    "age": [31,25, 31,22, 35, 28, 25, 31, 40],
    "score": [80, 90, 80, 70, 95,85, 90, 80, pd.NA],
    "date": ["2022-01-02", "2022-Mar-01", "2022-01-02", "2022-01-03", "2022-01-04", "2022-01-05", "2022-01-01", "2022-01-02", "2022-01-06"],
    "city": ["Chicago", "Boston", "Chicago", "Seattle", "Boston", "Chicago", "Chicago", "Chicago", "Boston"]

})

df1

    name  age score         date     city
0   mary   31    80   2022-01-02  Chicago
1   John   25    90  2022-Mar-01   Boston
2   mary   31    80   2022-01-02  Chicago
3   Jane   22    70   2022-01-03  Seattle
4    bob   35    95   2022-01-04   Boston
5  Alice   28    85   2022-01-05  Chicago
6   John   25    90   2022-01-01  Chicago
7   mary   31    80   2022-01-02  Chicago
8   <NA>   40  <NA>   2022-01-06   Boston

In [189]:
data = {
    "Name": ["John", "Emma", "John", "Liam", "Emma", "Olivia", "John"],
    "Age": [28, 22, 28, 32, 22, 27, 28],
    "City": ["Chicago", "Boston", "Chicago", "Seattle", "Boston", "Chicago", "Chicago"]
}

df2 = pd.DataFrame(data)
print("Original data:\n", df2)

Original data:
      Name  Age     City
0    John   28  Chicago
1    Emma   22   Boston
2    John   28  Chicago
3    Liam   32  Seattle
4    Emma   22   Boston
5  Olivia   27  Chicago
6    John   28  Chicago

# 1. Assess Data Quality

The first step in data cleaning is to assess the quality of your data. This involves checking for:

Missing Values: Identify any blank or null values in the dataset. Missing values can be due to various reasons such as incomplete data collection, data entry errors or data loss during transmission.
Incorrect Values: Check for values that are outside the expected range or are inconsistent with the data type.
Inconsistencies in Data Format: Verify that the data format is consistent throughout the dataset.

In [190]:
df1["Is_Duplicate"] = df1.duplicated()
print("Data after marking duplicate rows:\n", df1)

Data after marking duplicate rows:
     name  age score         date     city  Is_Duplicate
0   mary   31    80   2022-01-02  Chicago         False
1   John   25    90  2022-Mar-01   Boston         False
2   mary   31    80   2022-01-02  Chicago          True
3   Jane   22    70   2022-01-03  Seattle         False
4    bob   35    95   2022-01-04   Boston         False
5  Alice   28    85   2022-01-05  Chicago         False
6   John   25    90   2022-01-01  Chicago         False
7   mary   31    80   2022-01-02  Chicago          True
8   <NA>   40  <NA>   2022-01-06   Boston         False

Why is the above data showing Is_Duplicate false for df1? This is because even the name, age, score, date, and city for entry "mary" here the id is different.

In [191]:
# Detect duplicate rows
df2["Is_Duplicate"] = df2.duplicated()
print("Data after marking duplicate rows:\n", df2)

Data after marking duplicate rows:
      Name  Age     City  Is_Duplicate
0    John   28  Chicago         False
1    Emma   22   Boston         False
2    John   28  Chicago          True
3    Liam   32  Seattle         False
4    Emma   22   Boston          True
5  Olivia   27  Chicago         False
6    John   28  Chicago          True

# Removing Duplicate Data: The drop_duplicates Method
The drop_duplicates method is used to remove duplicate rows and return a deduplicated DataFrame.

In [192]:
# Remove duplicate rows
df2_deduplicated = df2.drop_duplicates()
print("Data after removing duplicate rows:\n", df2_deduplicated)

Data after removing duplicate rows:
      Name  Age     City  Is_Duplicate
0    John   28  Chicago         False
1    Emma   22   Boston         False
2    John   28  Chicago          True
3    Liam   32  Seattle         False
4    Emma   22   Boston          True
5  Olivia   27  Chicago         False

By default, drop_duplicates keeps the first occurrence of each duplicate row.

Keeping the Last Occurrence
You can keep the last occurrence of each duplicate by setting the keep parameter to 'last':

In [193]:
# Keep the last occurrence of duplicate rows
df_last = df2.drop_duplicates(keep="last")
print("Data after keeping the last duplicate record:\n", df_last)

Data after keeping the last duplicate record:
      Name  Age     City  Is_Duplicate
0    John   28  Chicago         False
1    Emma   22   Boston         False
3    Liam   32  Seattle         False
4    Emma   22   Boston          True
5  Olivia   27  Chicago         False
6    John   28  Chicago          True

# Detecting Duplicates Based on Specific Columns
If you want to detect duplicates based on specific columns only, you can use the subset parameter. For example:

In [194]:

# Remove duplicate rows with name
df2_deduplicated = df2.drop_duplicates(subset=["Name", "City"])
print("Data after removing duplicate rows:\n", df2_deduplicated)

Data after removing duplicate rows:
      Name  Age     City  Is_Duplicate
0    John   28  Chicago         False
1    Emma   22   Boston         False
3    Liam   32  Seattle         False
5  Olivia   27  Chicago         False

In [195]:
# Remove duplicate rows with name
df1 = df1.drop_duplicates(subset=["name", "city", "age", "score"])
print("Data after removing duplicate rows:\n", df1)

Data after removing duplicate rows:
     name  age score         date     city  Is_Duplicate
0   mary   31    80   2022-01-02  Chicago         False
1   John   25    90  2022-Mar-01   Boston         False
3   Jane   22    70   2022-01-03  Seattle         False
4    bob   35    95   2022-01-04   Boston         False
5  Alice   28    85   2022-01-05  Chicago         False
6   John   25    90   2022-01-01  Chicago         False
8   <NA>   40  <NA>   2022-01-06   Boston         False

Resetting Index After Removing Duplicates
After removing duplicate data, the original index may no longer be continuous. You can reset the index using the reset_index method:

In [196]:
# Reset index
df_cleaned = df2_deduplicated.reset_index(drop=True)
print("Data after resetting index:\n", df_cleaned)

Data after resetting index:
      Name  Age     City  Is_Duplicate
0    John   28  Chicago         False
1    Emma   22   Boston         False
2    Liam   32  Seattle         False
3  Olivia   27  Chicago         False

# Fill Missing Values: Replace NaN with a default value.

In [197]:
df1.isna()

    name    age  score   date   city  Is_Duplicate
0  False  False  False  False  False         False
1  False  False  False  False  False         False
3  False  False  False  False  False         False
4  False  False  False  False  False         False
5  False  False  False  False  False         False
6  False  False  False  False  False         False
8   True  False   True  False  False         False

In [ ]:
df1["score"] = df1["score"].fillna(0)  # Avoid NaN in calculated values

/var/folders/4m/dgr_zd0s13d819vvwn8l11n4kjnz1b/T/ipykernel_55627/17165948.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1["score"] = df1["score"].fillna(0)  # Avoid NaN in calculated values
/var/folders/4m/dgr_zd0s13d819vvwn8l11n4kjnz1b/T/ipykernel_55627/17165948.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["score"] = df1["score"].fillna(0)  # Avoid NaN in calculated values

This is not a best practice 
SettingWithCopyWarning → you’re modifying a slice → fix with .copy() or .loc
FutureWarning → column type issue → fix with pd.to_numeric()

In [219]:
df1 = df1.copy()

df1["score"] = pd.to_numeric(df1["score"], errors="coerce").fillna(0)

In [199]:
df1.fillna("Unknown", inplace=True)  # Replace NaN with a placeholder string
df1

/var/folders/4m/dgr_zd0s13d819vvwn8l11n4kjnz1b/T/ipykernel_55627/3576152886.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.fillna("Unknown", inplace=True)  # Replace NaN with a placeholder string

      name  age  score         date     city  Is_Duplicate
0     mary   31     80   2022-01-02  Chicago         False
1     John   25     90  2022-Mar-01   Boston         False
3     Jane   22     70   2022-01-03  Seattle         False
4      bob   35     95   2022-01-04   Boston         False
5    Alice   28     85   2022-01-05  Chicago         False
6     John   25     90   2022-01-01  Chicago         False
8  Unknown   40      0   2022-01-06   Boston         False

In [220]:
df1 = df1.copy()
df1.fillna("Unknown", inplace=True)  # Replace NaN with a placeholder string
df1

    name  age  score       date     city  Is_Duplicate  year
0   Mary   31     80 2022-01-02  Chicago         False  2022
1   John   25     90 2022-03-01   Boston         False  2022
3   Jane   22     70 2022-01-03  Seattle         False  2022
4    Bob   35     95 2022-01-04   Boston         False  2022
5  Alice   28     85 2022-01-05  Chicago         False  2022
6   John   25     90 2022-01-01  Chicago         False  2022

In [200]:
df1.isna()

    name    age  score   date   city  Is_Duplicate
0  False  False  False  False  False         False
1  False  False  False  False  False         False
3  False  False  False  False  False         False
4  False  False  False  False  False         False
5  False  False  False  False  False         False
6  False  False  False  False  False         False
8  False  False  False  False  False         False

In [201]:
df1

      name  age  score         date     city  Is_Duplicate
0     mary   31     80   2022-01-02  Chicago         False
1     John   25     90  2022-Mar-01   Boston         False
3     Jane   22     70   2022-01-03  Seattle         False
4      bob   35     95   2022-01-04   Boston         False
5    Alice   28     85   2022-01-05  Chicago         False
6     John   25     90   2022-01-01  Chicago         False
8  Unknown   40      0   2022-01-06   Boston         False

2. Remove Irrelevant Data
# 3. Fix Structural Errors

In [221]:
df1 = df1.copy()
df1["name"] = df1["name"].str.title()
df1

    name  age  score       date     city  Is_Duplicate  year
0   Mary   31     80 2022-01-02  Chicago         False  2022
1   John   25     90 2022-03-01   Boston         False  2022
3   Jane   22     70 2022-01-03  Seattle         False  2022
4    Bob   35     95 2022-01-04   Boston         False  2022
5  Alice   28     85 2022-01-05  Chicago         False  2022
6   John   25     90 2022-01-01  Chicago         False  2022

In [203]:
df1 = df1[~((df1["name"] == "Unknown") & (df1["score"] == 0))]

df1

    name  age  score         date     city  Is_Duplicate
0   Mary   31     80   2022-01-02  Chicago         False
1   John   25     90  2022-Mar-01   Boston         False
3   Jane   22     70   2022-01-03  Seattle         False
4    Bob   35     95   2022-01-04   Boston         False
5  Alice   28     85   2022-01-05  Chicago         False
6   John   25     90   2022-01-01  Chicago         False

In [222]:
df1 = df1.copy()
df1["date"] = pd.to_datetime(df1["date"], errors="coerce", format="mixed")
df1

    name  age  score       date     city  Is_Duplicate  year
0   Mary   31     80 2022-01-02  Chicago         False  2022
1   John   25     90 2022-03-01   Boston         False  2022
3   Jane   22     70 2022-01-03  Seattle         False  2022
4    Bob   35     95 2022-01-04   Boston         False  2022
5  Alice   28     85 2022-01-05  Chicago         False  2022
6   John   25     90 2022-01-01  Chicago         False  2022

In [209]:
datatypes = df1.dtypes
datatypes

name                    object
age                      int64
score                    int64
date            datetime64[ns]
city                    object
Is_Duplicate              bool
dtype: object

In [223]:
df1 = df1.copy()
df1["year"] = df1["date"].dt.year
df1

    name  age  score       date     city  Is_Duplicate  year
0   Mary   31     80 2022-01-02  Chicago         False  2022
1   John   25     90 2022-03-01   Boston         False  2022
3   Jane   22     70 2022-01-03  Seattle         False  2022
4    Bob   35     95 2022-01-04   Boston         False  2022
5  Alice   28     85 2022-01-05  Chicago         False  2022
6   John   25     90 2022-01-01  Chicago         False  2022

5. Normalize Data
Data normalization organizes the dataset to reduce redundancy and ensure consistency making it easier to manage and analyze.

Split data into multiple tables, with each table storing specific types of information.
Ensure consistency across the dataset to support efficient querying and accurate analysis.

In [215]:
student_info = df1[['name', 'age', 'city']]
student_info

    name  age     city
0   Mary   31  Chicago
1   John   25   Boston
3   Jane   22  Seattle
4    Bob   35   Boston
5  Alice   28  Chicago
6   John   25  Chicago

In [216]:
student_score = df1[['name', 'score', 'date']]
student_info

    name  age     city
0   Mary   31  Chicago
1   John   25   Boston
3   Jane   22  Seattle
4    Bob   35   Boston
5  Alice   28  Chicago
6   John   25  Chicago

In [ ]:
# Data Cleaning Strategies
To ensure high-quality and reliable data follow these best practices:

Understand the data: Know the source, structure and domain of the data to identify potential quality issues and determine appropriate cleaning actions.
Document the process: Keep records of decisions, methods, assumptions and rules applied during data cleaning.
Prioritize critical issues: Focus first on major quality problems that could have a systemic impact on analysis or decision-making.
Automate where possible: Use scripts or tools for repetitive cleaning tasks to improve efficiency and consistency.
Collaborate with domain experts: Engage stakeholders or domain specialists to validate that the cleaned data meets business requirements.
Monitor and maintain: Continuously track data quality and perform cleaning periodically to ensure long-term accuracy and reliability.