In [17]:
import pandas as pd

data = pd.read_csv("data/thanksgiving.csv", encoding="Latin-1")
data.head(2)

,RespondentID,Do you celebrate Thanksgiving?,What is typically the main dish at your Thanksgiving dinner?,What is typically the main dish at your Thanksgiving dinner? - Other (please specify),How is the main dish typically cooked?,How is the main dish typically cooked? - Other (please specify),What kind of stuffing/dressing do you typically have?,What kind of stuffing/dressing do you typically have? - Other (please specify),What type of cranberry saucedo you typically have?,What type of cranberry saucedo you typically have? - Other (please specify),...,Have you ever tried to meet up with hometown friends on Thanksgiving night?,"Have you ever attended a ""Friendsgiving?""",Will you shop any Black Friday sales on Thanksgiving Day?,Do you work in retail?,Will you employer make you work on Black Friday?,How would you describe where you live?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region
0,4337954960,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,NaN,NaN,...,Yes,No,No,No,NaN,Suburban,18 - 29,Male,"$75,000 to $99,999",Middle Atlantic
1,4337951949,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Other (please specify),Homemade cranberry gelatin ring,...,No,No,Yes,No,NaN,Rural,18 - 29,Female,"$50,000 to $74,999",East South Central

In [4]:
data.columns

Index(['RespondentID', 'Do you celebrate Thanksgiving?',
       'What is typically the main dish at your Thanksgiving dinner?',
       'What is typically the main dish at your Thanksgiving dinner? - Other (please specify)',
       'How is the main dish typically cooked?',
       'How is the main dish typically cooked? - Other (please specify)',
       'What kind of stuffing/dressing do you typically have?',
       'What kind of stuffing/dressing do you typically have? - Other (please specify)',
       'What type of cranberry saucedo you typically have?',
       'What type of cranberry saucedo you typically have? - Other (please specify)',
       'Do you typically have gravy?',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Brussel sprouts',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Carrots',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Cauliflower',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Corn',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Cornbread',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Fruit salad',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Green beans/green bean casserole',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Macaroni and cheese',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Mashed potatoes',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Rolls/biscuits',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Squash',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Vegetable salad',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Yams/sweet potato casserole',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify)',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify).1',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Buttermilk',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Cherry',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Chocolate',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Coconut cream',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Key lime',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Peach',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pecan',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pumpkin',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Sweet Potato',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - None',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify)',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify).1',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Apple cobbler',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Blondies',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Brownies',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Carrot cake',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Cheesecake',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Cookies',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Fudge',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Ice cream',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Peach cobbler',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - None',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Other (please specify)',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Other (please specify).1',
       'Do you typically pray before or after the Thanksgiving meal?',
       'How far will you travel for Thanksgiving?',
       'Will you watch any of the following programs on Thanksgiving? Please select all that apply. - Macy's Parade',
       'What's the age cutoff at your "kids' table" at Thanksgiving?',
       'Have you ever tried to meet up with hometown friends on Thanksgiving night?',
       'Have you ever attended a "Friendsgiving?"',
       'Will you shop any Black Friday sales on Thanksgiving Day?',
       'Do you work in retail?',
       'Will you employer make you work on Black Friday?',
       'How would you describe where you live?', 'Age', 'What is your gender?',
       'How much total combined money did all members of your HOUSEHOLD earn last year?',
       'US Region'],
      dtype='object')

In [18]:
data['Do you celebrate Thanksgiving?'].value_counts()

Do you celebrate Thanksgiving?
Yes    980
No      78
Name: count, dtype: int64

In [19]:
data = data[data['Do you celebrate Thanksgiving?'] == 'Yes']
data

,RespondentID,Do you celebrate Thanksgiving?,What is typically the main dish at your Thanksgiving dinner?,What is typically the main dish at your Thanksgiving dinner? - Other (please specify),How is the main dish typically cooked?,How is the main dish typically cooked? - Other (please specify),What kind of stuffing/dressing do you typically have?,What kind of stuffing/dressing do you typically have? - Other (please specify),What type of cranberry saucedo you typically have?,What type of cranberry saucedo you typically have? - Other (please specify),...,Have you ever tried to meet up with hometown friends on Thanksgiving night?,"Have you ever attended a ""Friendsgiving?""",Will you shop any Black Friday sales on Thanksgiving Day?,Do you work in retail?,Will you employer make you work on Black Friday?,How would you describe where you live?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region
0,4337954960,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,NaN,NaN,...,Yes,No,No,No,NaN,Suburban,18 - 29,Male,"$75,000 to $99,999",Middle Atlantic
1,4337951949,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Other (please specify),Homemade cranberry gelatin ring,...,No,No,Yes,No,NaN,Rural,18 - 29,Female,"$50,000 to $74,999",East South Central
2,4337935621,Yes,Turkey,NaN,Roasted,NaN,Rice-based,NaN,Homemade,NaN,...,Yes,Yes,Yes,No,NaN,Suburban,18 - 29,Male,"$0 to $9,999",Mountain
3,4337933040,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$200,000 and up",Pacific
4,4337931983,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$100,000 to $124,999",Pacific
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1053,4335944082,Yes,Turkey,NaN,Roasted,NaN,Bread-based,NaN,Homemade,NaN,...,Yes,Yes,No,No,NaN,Rural,30 - 44,Female,"$100,000 to $124,999",Mountain
1054,4335943173,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,No,No,No,No,NaN,Suburban,60+,Female,"$50,000 to $74,999",Pacific
1055,4335943060,Yes,Other (please specify),Duck,Baked,NaN,Rice-based,NaN,NaN,NaN,...,Yes,Yes,Yes,No,NaN,Urban,60+,Male,"$100,000 to $124,999",Pacific
1056,4335934708,Yes,Turkey,NaN,Baked,NaN,NaN,NaN,Homemade,NaN,...,Yes,No,Yes,Yes,Yes,NaN,NaN,NaN,NaN,NaN
1057,4335894916,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,Yes,Yes,Yes,No,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
data["What is typically the main dish at your Thanksgiving dinner?"].value_counts()

What is typically the main dish at your Thanksgiving dinner?
Turkey                    859
Other (please specify)     35
Ham/Pork                   29
Tofurkey                   20
Chicken                    12
Roast beef                 11
I don't know                5
Turducken                   3
Name: count, dtype: int64

In [22]:
data = data[data["What is typically the main dish at your Thanksgiving dinner?"] == "I don't know"]
data

,RespondentID,Do you celebrate Thanksgiving?,What is typically the main dish at your Thanksgiving dinner?,What is typically the main dish at your Thanksgiving dinner? - Other (please specify),How is the main dish typically cooked?,How is the main dish typically cooked? - Other (please specify),What kind of stuffing/dressing do you typically have?,What kind of stuffing/dressing do you typically have? - Other (please specify),What type of cranberry saucedo you typically have?,What type of cranberry saucedo you typically have? - Other (please specify),...,Have you ever tried to meet up with hometown friends on Thanksgiving night?,"Have you ever attended a ""Friendsgiving?""",Will you shop any Black Friday sales on Thanksgiving Day?,Do you work in retail?,Will you employer make you work on Black Friday?,How would you describe where you live?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region
647,4336662967,Yes,I don't know,NaN,I don't know,NaN,NaN,NaN,NaN,NaN,...,Yes,Yes,Yes,Yes,Yes,Rural,30 - 44,Male,"$0 to $9,999",NaN
843,4336161556,Yes,I don't know,NaN,Roasted,NaN,Other (please specify),Asian styled,NaN,NaN,...,Yes,No,No,No,NaN,Suburban,18 - 29,Female,"$50,000 to $74,999",Pacific
884,4336083561,Yes,I don't know,NaN,I don't know,NaN,NaN,NaN,Homemade,NaN,...,No,No,Yes,No,NaN,Rural,18 - 29,Female,Prefer not to answer,West North Central
941,4336017089,Yes,I don't know,NaN,Fried,NaN,Bread-based,NaN,Canned,NaN,...,No,Yes,No,Yes,Doesn't apply,Rural,18 - 29,Male,"$0 to $9,999",NaN
1023,4335957772,Yes,I don't know,NaN,I don't know,NaN,Bread-based,NaN,Canned,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
data["What is typically the main dish at your Thanksgiving dinner? - Other (please specify)"].value_counts()

What is typically the main dish at your Thanksgiving dinner? - Other (please specify)
Turkey and Ham                                                                           2
Prime Rib                                                                                2
seafood                                                                                  2
Turkey & Ham or Seafood Hotdish (a secret family recipe).                                1
Homemade vegan entree                                                                    1
head cheese                                                                              1
Lentil Loaf                                                                              1
changes every year                                                                       1
Turkey and Vegetarian Turkey                                                             1
steak                                                                                    1
Venison                                                                                  1
A turkey and a ham. Always.                                                              1
prime rib                                                                                1
goose                                                                                    1
Varies significantly by year as one group of people we tend to be with are vegetarian    1
salmon                                                                                   1
turkey, ham. vegetarian for me.                                                          1
No predictable main dish                                                                 1
Varies                                                                                   1
It varies, ham or turkey or boston butt                                                  1
Steak                                                                                    1
This year we are having baked lasagna, diff every year                                   1
Both turkey and a vegetarian nut loaf                                                    1
Chicken Dressing                                                                         1
alternate turkey & ham                                                                   1
gumbo                                                                                    1
Restaurant with various choices.                                                         1
always different                                                                         1
A wild game bird which changes every year.                                               1
fish                                                                                     1
some kind of lentil or vegetable stew                                                    1
Duck                                                                                     1
Name: count, dtype: int64

In [23]:
apple_isnull = pd.isnull(data['Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple'])

In [29]:
peacan_isnull = pd.isnull(data['Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pecan'])

In [35]:
cherry_isnull = pd.isnull(data['Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pumpkin'])

In [36]:
pie = apple_isnull & peacan_isnull & cherry_isnull
pie.value_counts()

False    3
True     2
Name: count, dtype: int64

In [37]:
pie = apple_isnull & peacan_isnull & cherry_isnull
pie.count()

np.int64(5)

🧠 What it does (simple)

👉 It counts how many times each unique age appears in the dataset.

In [52]:
data['Age'].value_counts()

Age
18 - 29    3
30 - 44    1
Name: count, dtype: int64

In [50]:
data['int_income'] = data['How much total combined money did all members of your HOUSEHOLD earn last year?'].value_counts()

In [51]:
data['int_income']

647    NaN
843    NaN
884    NaN
941    NaN
1023   NaN
Name: int_income, dtype: float64

In [45]:
data['int_income'].describe()

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: int_income, dtype: float64

In [53]:
less_150000 = data[data['int_income'] < 150000]
less_150000

Empty DataFrame
Columns: [RespondentID, Do you celebrate Thanksgiving?, What is typically the main dish at your Thanksgiving dinner?, What is typically the main dish at your Thanksgiving dinner? - Other (please specify), How is the main dish typically cooked?, How is the main dish typically cooked? - Other (please specify), What kind of stuffing/dressing do you typically have?, What kind of stuffing/dressing do you typically have? - Other (please specify), What type of cranberry saucedo you typically have?, What type of cranberry saucedo you typically have? - Other (please specify), Do you typically have gravy?, Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Brussel sprouts, Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Carrots, Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Cauliflower, Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Corn, Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Cornbread, Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Fruit salad, Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Green beans/green bean casserole, Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Macaroni and cheese, Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Mashed potatoes, Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Rolls/biscuits, Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Squash, Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Vegetable salad, Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Yams/sweet potato casserole, Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify), Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify).1, Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple, Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Buttermilk, Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Cherry, Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Chocolate, Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Coconut cream, Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Key lime, Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Peach, Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pecan, Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pumpkin, Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Sweet Potato, Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - None, Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify), Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify).1, Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Apple cobbler, Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Blondies, Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Brownies, Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Carrot cake, Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Cheesecake, Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Cookies, Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Fudge, Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Ice cream, Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Peach cobbler, Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - None, Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Other (please specify), Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Other (please specify).1, Do you typically pray before or after the Thanksgiving meal?, How far will you travel for Thanksgiving?, Will you watch any of the following programs on Thanksgiving? Please select all that apply. - Macy's Parade, What's the age cutoff at your "kids' table" at Thanksgiving?, Have you ever tried to meet up with hometown friends on Thanksgiving night?, Have you ever attended a "Friendsgiving?", Will you shop any Black Friday sales on Thanksgiving Day?, Do you work in retail?, Will you employer make you work on Black Friday?, How would you describe where you live?, Age, What is your gender?, How much total combined money did all members of your HOUSEHOLD earn last year?, US Region, int_income]
Index: []

[0 rows x 66 columns]