JOIN

In [1]:
import pandas as pd
import numpy as np

class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

In [2]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering',
                              'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
display('df1', 'df2')

df1
  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

df2
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [3]:
df3 = pd.merge(df1, df2)
df3

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

1. INNER JOIN

An INNER JOIN is one of the most commonly used joins in SQL. It returns only the rows that have matching values in both tables. If there is no match, the row is not included in the result set.
The INNER JOIN essentially combines the data from two or more tables based on a related column, and it filters out rows that do not satisfy the join condition.

Best Practices for Inner Join with Pandas

1. Checking for missing values: Before performing an inner join, it’s important to check for missing values in both data frames. Missing values can lead to inaccurate results or errors.
2. hoosing the right join type: Make sure to choose the right join type based on the data and analysis requirements. An inner join is suitable when you only want to keep the rows that have matching values in both data frames.
3. Renaming columns: If the column names in the two data frames are different, it’s a good practice to rename them to avoid confusion.
4. Dropping duplicate rows: If the two data frames contain duplicate rows, it’s a good practice to drop them before performing the join operation.

In [4]:
inner_join_df = pd.merge(df1, df2, on='employee', how='inner')
inner_join_df

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [5]:
inner_join_df_1 = pd.merge(df1, df2,  how='inner')
inner_join_df_1

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

2.LEFT JOIN

 A LEFT JOIN, also referred to as a LEFT OUTER JOIN, is a type of SQL join where all rows from the left table (table1) are returned regardless of whether there is a match in the right table (table2). It includes the matching rows from the right table based on a related column specified in the ON clause of the LEFT JOIN statement.

This join condition ensures that for each row from the left table, the LEFT JOIN includes the corresponding matching rows from the right table in the result set. If there is no match found in the right table, NULL values are returned for the columns from the right table.

In [6]:
left_join_df_1 = pd.merge(df1, df2,  how='left') 
left_join_df_1

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [7]:
# Left DataFrame
employees = pd.DataFrame({
    'Emp_ID': [101, 102, 103],
    'Name': ['John', 'Jane', 'Doe']
})

# Right DataFrame with a different key column name
salaries = pd.DataFrame({
    'Employee_ID': [102, 103, 104],
    'Salary': [50000, 60000, 70000]
})
employees

   Emp_ID  Name
0     101  John
1     102  Jane
2     103   Doe

In [8]:
salaries

   Employee_ID  Salary
0          102   50000
1          103   60000
2          104   70000

In [9]:
# Left Merge with different key column names
merged_data = pd.merge(employees, salaries, how='left', left_on='Emp_ID', right_on='Employee_ID')
print(merged_data)

   Emp_ID  Name  Employee_ID   Salary
0     101  John          NaN      NaN
1     102  Jane        102.0  50000.0
2     103   Doe        103.0  60000.0

Left join: Merging on Multiple Columns

In [10]:
# Left DataFrame
sales = pd.DataFrame({
    'Store': ['A', 'B', 'A'],
    'Date': ['2023-01-01', '2023-01-01', '2023-01-02'],
    'Sales': [100, 200, 150]
})

# Right DataFrame
targets = pd.DataFrame({
    'Store': ['A', 'B','F'],
    'Date': ['2023-01-01', '2023-01-01', '2023-01-02'],
    'Target': [120, 180, 200]
})

# Merging on multiple columns
merged_sales = pd.merge(sales, targets, how='left', on=['Store', 'Date'])
print(merged_sales)

  Store        Date  Sales  Target
0     A  2023-01-01    100   120.0
1     B  2023-01-01    200   180.0
2     A  2023-01-02    150     NaN

In [11]:
# Fill NaN values with 0
merged_sales['Target'] = merged_sales['Target'].fillna(0)
print(merged_sales)

  Store        Date  Sales  Target
0     A  2023-01-01    100   120.0
1     B  2023-01-01    200   180.0
2     A  2023-01-02    150     0.0

3.RIGHT JOIN

A RIGHT JOIN, also known as RIGHT OUTER JOIN, is a type of SQL join that returns all rows from the right table (table2) and includes matching rows from the left table (table1). The join condition is based on a related column between the two tables, specified in the ON clause of the RIGHT JOIN statement.

The RIGHT JOIN ensures that all rows from the right table are retained in the result set, and for each row from the right table, it includes the corresponding matching rows from the left table based on the join condition. If there is no match found in the left table, NULL values are returned for the columns from the left table.

In [12]:
right_join_df = pd.merge(df1, df2,  how='right')
right_join_df

  employee        group  hire_date
0     Lisa  Engineering       2004
1      Bob   Accounting       2008
2     Jake  Engineering       2012
3      Sue           HR       2014

In [13]:
# Merging on multiple columns
right_join_df_1 = pd.merge(sales, targets, how='right', on=['Store', 'Date'])
print(right_join_df_1)

  Store        Date  Sales  Target
0     A  2023-01-01  100.0     120
1     B  2023-01-01  200.0     180
2     F  2023-01-02    NaN     200

4.FULL JOIN - outrer

A FULL JOIN, also known as a FULL OUTER JOIN, is a type of SQL join that returns all rows from both the left table (table1) and the right table (table2). When there is a match between the tables based on the join condition, the result set includes the matched rows from both tables. When there is no match, the result set includes NULL values for columns from the table without a match.

In [14]:
# Merging on multiple columns
full_join_df_1 = pd.merge(sales, targets, how='outer', left_on=['Store', 'Date'], right_on=['Store', 'Date'])
print(full_join_df_1)

  Store        Date  Sales  Target
0     A  2023-01-01  100.0   120.0
1     A  2023-01-02  150.0     NaN
2     B  2023-01-01  200.0   180.0
3     F  2023-01-02    NaN   200.0

In [15]:
outer_join_df_1 = pd.merge(df1, df2,  how='outer') 
outer_join_df_1

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

EXP

In [16]:
import pandas as pd

A = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']})
B = pd.DataFrame({'ID': [2, 3, 4], 'Score': [85, 90, 95]})

print("DataFrame A:")
print(A)
print("DataFrame B:")
print(B)
print("Left Merge")

# Left Merge
print(pd.merge(A, B, how='left', on='ID'))

print("Right Merge")
# Right Merge
print(pd.merge(A, B, how='right', on='ID'))

print("Inner Merge")
# Inner Merge
print(pd.merge(A, B, how='inner', on='ID'))

print("Outer Merge")
# Outer Merge
print(pd.merge(A, B, how='outer', on='ID'))

DataFrame A:
   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie
DataFrame B:
   ID  Score
0   2     85
1   3     90
2   4     95
Left Merge
   ID     Name  Score
0   1    Alice    NaN
1   2      Bob   85.0
2   3  Charlie   90.0
Right Merge
   ID     Name  Score
0   2      Bob     85
1   3  Charlie     90
2   4      NaN     95
Inner Merge
   ID     Name  Score
0   2      Bob     85
1   3  Charlie     90
Outer Merge
   ID     Name  Score
0   1    Alice    NaN
1   2      Bob   85.0
2   3  Charlie   90.0
3   4      NaN   95.0