In [12]:
import pandas as pd

titianic_data = pd.read_csv("data/titanic_survival.csv")
titianic_data.head(5)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

# Find missing values

In [13]:
titianic_data.isnull()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,False,False,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False,True,True,False
3,False,False,False,False,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1306,False,False,False,False,False,False,False,False,False,True,False,True,False,True
1307,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1308,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1309,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [14]:
titianic_data.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='object')

# Create one method to get number of null values

In [17]:
age = titianic_data["age"]
is_null_age = age.isnull()
print(is_null_age)

0       False
1       False
2       False
3       False
4       False
        ...
1305     True
1306    False
1307    False
1308    False
1309     True
Name: age, Length: 1310, dtype: bool

In [19]:
age.dtype

dtype('float64')

In [ ]:
titianic_data.isna()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,False,False,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False,True,True,False
3,False,False,False,False,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1306,False,False,False,False,False,False,False,False,False,True,False,True,False,True
1307,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1308,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1309,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [22]:
def find_total_null_value(column):
    return titianic_data[column].isnull().sum()

In [23]:
## find sex null count
find_total_null_value("sex")

np.int64(1)

In [24]:
## find age null count
find_total_null_value("age")

np.int64(264)

# Calculate average age

In [25]:
mean_age = sum(titianic_data["age"]) / len(titianic_data["age"]) 
print(mean_age)

nan

In [26]:
mean_age = titianic_data["age"].mean()
print(mean_age)

29.8811345124283

In [28]:
def find_mean(colom):
    return titianic_data[colom].mean()

In [29]:
find_mean("fare")

np.float64(33.29547928134557)

In [30]:
titianic_data.head(2)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"

# Find number of people survived in each class

In [42]:
classes = [1, 2, 3]

In [46]:
def total_survival_data():
    survived_num_group1 = 0
    survived_num_group2 = 0
    survived_num_group3 = 0
    for i, row in titianic_data.iterrows():
        
        if row["pclass"] == classes[0] and row["survived"] == 1:
            survived_num_group1 += 1
            
        elif row["pclass"] == classes[1] and row["survived"] == 1:
            survived_num_group2 += 1
            
        elif row["pclass"] == classes[2] and row["survived"] == 1:
            survived_num_group3 += 1

    print(f'Class 1: {survived_num_group1}')
    print(f'Class 2: {survived_num_group2}')
    print(f'Class 3: {survived_num_group3}')

In [47]:
total_survival_data()

Class 1: 200
Class 2: 119
Class 3: 181