In [49]:
import pandas as pd

titianic_data = pd.read_csv("data/titanic_survival.csv")
titianic_data.head(5)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

# Find number of people survived in each class

In [50]:
classes = [1, 2, 3]
def total_survival_data():
    survived_num_group1 = 0
    survived_num_group2 = 0
    survived_num_group3 = 0
    for i, row in titianic_data.iterrows():
        
        if row["pclass"] == classes[0] and row["survived"] == 1:
            survived_num_group1 += 1
            
        elif row["pclass"] == classes[1] and row["survived"] == 1:
            survived_num_group2 += 1
            
        elif row["pclass"] == classes[2] and row["survived"] == 1:
            survived_num_group3 += 1

    print(f'Class 1: {survived_num_group1}')
    print(f'Class 2: {survived_num_group2}')
    print(f'Class 3: {survived_num_group3}')

In [51]:
total_survival_data()

Class 1: 200
Class 2: 119
Class 3: 181

In [52]:
print(type(total_survival_data))

<class 'function'>

In [53]:
mean_age = titianic_data["age"].mean()
print(mean_age)

29.8811345124283

 This is a Pandas function used to summarize data (like Excel pivot tables)
 index="pclass" - Groups data by passenger class (pclass) -  Example values: 1, 2, 3
 values="fare" - The column you want to analyze - Here: ticket fare
 aggfunc=numpy.mean - The operation to apply on grouped data - Here: average (mean)

 1. Basic Syntax
 df.pivot_table(index, values, aggfunc)

2. Important Parameters

In [54]:
import numpy
class_fares = titianic_data.pivot_table(index="pclass", values="fare", aggfunc=numpy.mean)
print(class_fares)

             fare
pclass
1.0     87.508992
2.0     21.179196
3.0     13.302889

/var/folders/4m/dgr_zd0s13d819vvwn8l11n4kjnz1b/T/ipykernel_21959/732851202.py:2: FutureWarning: The provided callable <function mean at 0x10554aa20> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  class_fares = titianic_data.pivot_table(index="pclass", values="fare", aggfunc=numpy.mean)

3. Multiple grouping

In [55]:
class_fares_with_sex_pclass = titianic_data.pivot_table(index=["pclass", "sex"], values="fare", aggfunc="mean")
print(class_fares_with_sex_pclass)

                     fare
pclass sex
1.0    female  109.412385
       male     69.888385
2.0    female   23.234827
       male     19.904946
3.0    female   15.324250
       male     12.415462

4. Multiple values

In [56]:
class_fares_and_age_with_pclass  = titianic_data.pivot_table(index="pclass", values=["fare", "age"], aggfunc="mean")
print(class_fares_and_age_with_pclass)

              age       fare
pclass
1.0     39.159918  87.508992
2.0     29.506705  21.179196
3.0     24.816367  13.302889

🔹 5. Columns parameter (like Excel pivot columns)

In [57]:
spec = titianic_data.pivot_table(index="pclass", columns="sex", values="fare", aggfunc="mean")
print(spec)

sex         female       male
pclass
1.0     109.412385  69.888385
2.0      23.234827  19.904946
3.0      15.324250  12.415462

6. Fill missing values

In [58]:
without_filling = titianic_data.pivot_table(index="pclass", values="fare", aggfunc="mean", fill_value=0)
print(without_filling)

             fare
pclass
1.0     87.508992
2.0     21.179196
3.0     13.302889

7. Margins (totals)

In [59]:
with_margin = titianic_data.pivot_table(index="pclass", values="fare", aggfunc="mean", margins=True)
print(with_margin)

             fare
pclass
1.0     87.508992
2.0     21.179196
3.0     13.302889
All     33.295479

In [60]:
port_status = titianic_data.pivot_table(index="embarked", values={"fare", "survived"}, aggfunc= numpy.sum)
print(port_status)

                fare  survived
embarked
C         16830.7922     150.0
Q          1526.3085      44.0
S         25033.3862     304.0

/var/folders/4m/dgr_zd0s13d819vvwn8l11n4kjnz1b/T/ipykernel_21959/3409328388.py:1: FutureWarning: The provided callable <function sum at 0x105549620> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  port_status = titianic_data.pivot_table(index="embarked", values={"fare", "survived"}, aggfunc= numpy.sum)

# DataFrame.dropna(axis=0 or axis='index') - axis=1

In [61]:
drop_na_rows = titianic_data.dropna(axis=0)
drop_na_rows

Empty DataFrame
Columns: [pclass, survived, name, sex, age, sibsp, parch, ticket, fare, cabin, embarked, boat, body, home.dest]
Index: []

In [62]:
drop_na_columns = titianic_data.dropna(axis=1)
drop_na_columns

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[1310 rows x 0 columns]

# dropna(axis=..., subset=["name"])

✔️ subset=["name"]
Tells Pandas:
👉 “Only check the name column”

So:

If name is missing → row will be removed ❌
If other columns are missing → row stays ✅

In [63]:
titianic_data.dropna(axis=0, subset=["name"])

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3.0,0.0,"Zabour, Miss. Hileni",female,14.5000,1.0,0.0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3.0,0.0,"Zabour, Miss. Thamine",female,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3.0,0.0,"Zakarian, Mr. Mapriededer",male,26.5000,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3.0,0.0,"Zakarian, Mr. Ortin",male,27.0000,0.0,0.0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3.0,0.0,"Zimmerman, Mr. Leo",male,29.0000,0.0,0.0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [65]:
new_titianic_data = titianic_data.dropna(axis=0, subset=["age", "sex"])
new_titianic_data

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1301,3.0,0.0,"Youseff, Mr. Gerious",male,45.5000,0.0,0.0,2628,7.2250,NaN,C,NaN,312.0,NaN
1304,3.0,0.0,"Zabour, Miss. Hileni",female,14.5000,1.0,0.0,2665,14.4542,NaN,C,NaN,328.0,NaN
1306,3.0,0.0,"Zakarian, Mr. Mapriededer",male,26.5000,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3.0,0.0,"Zakarian, Mr. Ortin",male,27.0000,0.0,0.0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3.0,0.0,"Zimmerman, Mr. Leo",male,29.0000,0.0,0.0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [66]:
print(new_titianic_data.shape)

(1046, 14)

# DataFrame.loc[]

What it does:
- Sorts the DataFrame by age
- ascending=False → highest age first (descending order)
- inplace=False → creates a new DataFrame (does NOT modify original)

👉 So:
new_titianic_data = sorted version of your data (oldest → youngest)

In [68]:
new_titianic_data = titianic_data.sort_values("age", inplace=False, ascending=False)
new_titianic_data

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
14,1.0,1.0,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0.0,0.0,27042,30.0000,A23,S,B,NaN,"Hessle, Yorks"
61,1.0,1.0,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1.0,0.0,19877,78.8500,C46,S,6,NaN,"Little Onn Hall, Staffs"
1235,3.0,0.0,"Svensson, Mr. Johan",male,74.0,0.0,0.0,347060,7.7750,NaN,S,NaN,NaN,NaN
135,1.0,0.0,"Goldschmidt, Mr. George B",male,71.0,0.0,0.0,PC 17754,34.6542,A5,C,NaN,NaN,"New York, NY"
9,1.0,0.0,"Artagaveytia, Mr. Ramon",male,71.0,0.0,0.0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1297,3.0,0.0,"Wiseman, Mr. Phillippe",male,NaN,0.0,0.0,A/4. 34244,7.2500,NaN,S,NaN,NaN,NaN
1302,3.0,0.0,"Yousif, Mr. Wazli",male,NaN,0.0,0.0,2647,7.2250,NaN,C,NaN,NaN,NaN
1303,3.0,0.0,"Yousseff, Mr. Gerious",male,NaN,0.0,0.0,2627,14.4583,NaN,C,NaN,NaN,NaN
1305,3.0,0.0,"Zabour, Miss. Thamine",female,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN
1309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

🧠 What is .loc?

👉 .loc is used to select rows (and columns) by LABEL (index name)

| Expression | Meaning                    |
| ---------- | -------------------------- |
| `.loc[0]`  | row with index = 0         |
| `.iloc[0]` | first row (position-based) |

🔥 Example

After sorting:

index   name    age
2       Bob     60
0       John    45
1       Alice   30

👉 .loc[0]
John    45

👉 .iloc[0]
Bob     60

 🧠 Final takeaway
.loc[] → uses index label
.iloc[] → uses position
Sorting does NOT change index unless you reset it

In [69]:
new_titianic_data.loc[0]

pclass                                 1.0
survived                               1.0
name         Allen, Miss. Elisabeth Walton
sex                                 female
age                                   29.0
sibsp                                  0.0
parch                                  0.0
ticket                               24160
fare                              211.3375
cabin                                   B5
embarked                                 S
boat                                     2
body                                   NaN
home.dest                     St Louis, MO
Name: 0, dtype: object

In [73]:
new_titianic_data.loc[14:9]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
14,1.0,1.0,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0.0,0.0,27042,30.0000,A23,S,B,NaN,"Hessle, Yorks"
61,1.0,1.0,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1.0,0.0,19877,78.8500,C46,S,6,NaN,"Little Onn Hall, Staffs"
1235,3.0,0.0,"Svensson, Mr. Johan",male,74.0,0.0,0.0,347060,7.7750,NaN,S,NaN,NaN,NaN
135,1.0,0.0,"Goldschmidt, Mr. George B",male,71.0,0.0,0.0,PC 17754,34.6542,A5,C,NaN,NaN,"New York, NY"
9,1.0,0.0,"Artagaveytia, Mr. Ramon",male,71.0,0.0,0.0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"

# DataFrame.iloc[0]

In [70]:
new_titianic_data.iloc[0]

pclass                                        1.0
survived                                      1.0
name         Barkworth, Mr. Algernon Henry Wilson
sex                                          male
age                                          80.0
sibsp                                         0.0
parch                                         0.0
ticket                                      27042
fare                                         30.0
cabin                                         A23
embarked                                        S
boat                                            B
body                                          NaN
home.dest                           Hessle, Yorks
Name: 14, dtype: object

In [74]:
first_10_rows = new_titianic_data.iloc[0:10]
first_10_rows

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
14,1.0,1.0,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0.0,0.0,27042,30.0000,A23,S,B,NaN,"Hessle, Yorks"
61,1.0,1.0,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1.0,0.0,19877,78.8500,C46,S,6,NaN,"Little Onn Hall, Staffs"
1235,3.0,0.0,"Svensson, Mr. Johan",male,74.0,0.0,0.0,347060,7.7750,NaN,S,NaN,NaN,NaN
135,1.0,0.0,"Goldschmidt, Mr. George B",male,71.0,0.0,0.0,PC 17754,34.6542,A5,C,NaN,NaN,"New York, NY"
9,1.0,0.0,"Artagaveytia, Mr. Ramon",male,71.0,0.0,0.0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"
727,3.0,0.0,"Connors, Mr. Patrick",male,70.5,0.0,0.0,370369,7.7500,NaN,Q,NaN,171.0,NaN
81,1.0,0.0,"Crosby, Capt. Edward Gifford",male,70.0,1.0,1.0,WE/P 5735,71.0000,B22,S,NaN,269.0,"Milwaukee, WI"
506,2.0,0.0,"Mitchell, Mr. Henry Michael",male,70.0,0.0,0.0,C.A. 24580,10.5000,NaN,S,NaN,NaN,"Guernsey / Montclair, NJ and/or Toledo, Ohio"
285,1.0,0.0,"Straus, Mr. Isidor",male,67.0,1.0,0.0,PC 17483,221.7792,C55 C57,S,NaN,96.0,"New York, NY"
594,2.0,0.0,"Wheadon, Mr. Edward H",male,66.0,0.0,0.0,C.A. 24579,10.5000,NaN,S,NaN,NaN,"Guernsey, England / Edgewood, RI"

# DataFrame.reset_index(drop=True)

In [75]:
new_titianic_data.reset_index()

,index,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,14,1.0,1.0,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0.0,0.0,27042,30.0000,A23,S,B,NaN,"Hessle, Yorks"
1,61,1.0,1.0,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1.0,0.0,19877,78.8500,C46,S,6,NaN,"Little Onn Hall, Staffs"
2,1235,3.0,0.0,"Svensson, Mr. Johan",male,74.0,0.0,0.0,347060,7.7750,NaN,S,NaN,NaN,NaN
3,135,1.0,0.0,"Goldschmidt, Mr. George B",male,71.0,0.0,0.0,PC 17754,34.6542,A5,C,NaN,NaN,"New York, NY"
4,9,1.0,0.0,"Artagaveytia, Mr. Ramon",male,71.0,0.0,0.0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,1297,3.0,0.0,"Wiseman, Mr. Phillippe",male,NaN,0.0,0.0,A/4. 34244,7.2500,NaN,S,NaN,NaN,NaN
1306,1302,3.0,0.0,"Yousif, Mr. Wazli",male,NaN,0.0,0.0,2647,7.2250,NaN,C,NaN,NaN,NaN
1307,1303,3.0,0.0,"Yousseff, Mr. Gerious",male,NaN,0.0,0.0,2627,14.4583,NaN,C,NaN,NaN,NaN
1308,1305,3.0,0.0,"Zabour, Miss. Thamine",female,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN
1309,1309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:
reindexed = new_titianic_data.reset_index(drop=True)
reindexed

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0.0,0.0,27042,30.0000,A23,S,B,NaN,"Hessle, Yorks"
1,1.0,1.0,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1.0,0.0,19877,78.8500,C46,S,6,NaN,"Little Onn Hall, Staffs"
2,3.0,0.0,"Svensson, Mr. Johan",male,74.0,0.0,0.0,347060,7.7750,NaN,S,NaN,NaN,NaN
3,1.0,0.0,"Goldschmidt, Mr. George B",male,71.0,0.0,0.0,PC 17754,34.6542,A5,C,NaN,NaN,"New York, NY"
4,1.0,0.0,"Artagaveytia, Mr. Ramon",male,71.0,0.0,0.0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,3.0,0.0,"Wiseman, Mr. Phillippe",male,NaN,0.0,0.0,A/4. 34244,7.2500,NaN,S,NaN,NaN,NaN
1306,3.0,0.0,"Yousif, Mr. Wazli",male,NaN,0.0,0.0,2647,7.2250,NaN,C,NaN,NaN,NaN
1307,3.0,0.0,"Yousseff, Mr. Gerious",male,NaN,0.0,0.0,2627,14.4583,NaN,C,NaN,NaN,NaN
1308,3.0,0.0,"Zabour, Miss. Thamine",female,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN
1309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
reindexed.iloc[0:5, 0:3]

   pclass  survived                                               name
0     1.0       1.0               Barkworth, Mr. Algernon Henry Wilson
1     1.0       1.0  Cavendish, Mrs. Tyrell William (Julia Florence...
2     3.0       0.0                                Svensson, Mr. Johan
3     1.0       0.0                          Goldschmidt, Mr. George B
4     1.0       0.0                            Artagaveytia, Mr. Ramon

# DataFrame.apply()

# Retrive XX th column

In [80]:
def row_100(column):
    # extract 100th data 
    item = column.iloc[99]
    return item

In [81]:
row_100_var = titianic_data.apply(row_100)
row_100_var

pclass                                                     1.0
survived                                                   1.0
name         Duff Gordon, Lady. (Lucille Christiana Sutherl...
sex                                                     female
age                                                       48.0
sibsp                                                      1.0
parch                                                      0.0
ticket                                                   11755
fare                                                      39.6
cabin                                                      A16
embarked                                                     C
boat                                                         1
body                                                       NaN
home.dest                                       London / Paris
dtype: object

🧠 What this code does (simple idea)

👉 It counts how many missing values (NaN) are present in each column of your DataFrame.

⚡ Easier way (recommended)

You don’t actually need a custom function. Pandas already has this:

titianic_data.isnull().sum()


👉 Same result, simpler and faster 👍

🧠 Final takeaway
apply() → runs function on each column
pd.isnull() → finds missing values
Your code → counts nulls column-wise

🔁 What .apply() does
column_null_count = titianic_data.apply(null_count)


👉 .apply():

Runs null_count() on each column
Collects results

In [ ]:
import pandas as pd

def null_count(column):
    column_null = pd.isnull(column)
    null = column[column_null]
    return len(null)

In [85]:
column_null_count = titianic_data.apply(null_count)
print(column_null_count)

pclass          1
survived        1
name            1
sex             1
age           264
sibsp           1
parch           1
ticket          1
fare            2
cabin        1015
embarked        3
boat          824
body         1189
home.dest     565
dtype: int64

# DataFrame.apply(function, axis=1)

In [86]:
def is_minor(row):
    if row["age"] < 18:
        return True
    else:
        return False

In [87]:
minors = titianic_data.apply(is_minor, axis=1)
minors

0       False
1        True
2        True
3       False
4       False
        ...
1305    False
1306    False
1307    False
1308    False
1309    False
Length: 1310, dtype: bool

In [89]:
def which_class(row):
    pclass = row['pclass']

    if pd.isnull(pclass):
        return "Unknown"
    elif pclass == 1:
        return '1st class'
    elif pclass == 2:
        return '2nd class'
    elif pclass == 3:
        return '3rd class'

In [90]:
with_class = titianic_data.apply(which_class, axis=1)
with_class

0       1st class
1       1st class
2       1st class
3       1st class
4       1st class
          ...
1305    3rd class
1306    3rd class
1307    3rd class
1308    3rd class
1309      Unknown
Length: 1310, dtype: object