In [142]:
import pandas as pd
s = pd.Series([
    "  Apple iPhone 15 Pro 256GB  ",
    "SAMSUNG Galaxy-S24 Ultra (512GB)",
    None,
    "OnePlus 12 12GB/256GB - Black"
], name="title")

In [143]:
s_clean = s.str.strip().str.casefold()
s_clean

0           apple iphone 15 pro 256gb
1    samsung galaxy-s24 ultra (512gb)
2                                None
3       oneplus 12 12gb/256gb - black
Name: title, dtype: object

In [144]:
s_clean = s.str.strip().str.lower()
s_clean

0           apple iphone 15 pro 256gb
1    samsung galaxy-s24 ultra (512gb)
2                                None
3       oneplus 12 12gb/256gb - black
Name: title, dtype: object

In [145]:
s_clean = s.str.strip().str.upper()
s_clean

0           APPLE IPHONE 15 PRO 256GB
1    SAMSUNG GALAXY-S24 ULTRA (512GB)
2                                None
3       ONEPLUS 12 12GB/256GB - BLACK
Name: title, dtype: object

In [146]:
s_clean = s.str.strip().str.title()
s_clean

0           Apple Iphone 15 Pro 256Gb
1    Samsung Galaxy-S24 Ultra (512Gb)
2                                None
3       Oneplus 12 12Gb/256Gb - Black
Name: title, dtype: object

In [147]:

s_clean = s.str.strip().str.capitalize()
s_clean

0           Apple iphone 15 pro 256gb
1    Samsung galaxy-s24 ultra (512gb)
2                                None
3       Oneplus 12 12gb/256gb - black
Name: title, dtype: object

In [148]:

s_clean = s.str.strip().str.swapcase()
s_clean

0           aPPLE IpHONE 15 pRO 256gb
1    samsung gALAXY-s24 uLTRA (512gb)
2                                None
3       oNEpLUS 12 12gb/256gb - bLACK
Name: title, dtype: object

Search and Pattern Matching

* str.contains(pat, case=True, regex=True, na=False)
* str.startswith(pat), str.endswith(pat)
* str.match(pat) (start of string), str.fullmatch(pat) (entire string)
* str.count(pat) (number of matches)
* str.findall(pat) (list of matches)

In [149]:
str_pattern = s.str.contains(r"\bgalaxy\b", case=False, na=False)
str_pattern

0    False
1     True
2    False
3    False
Name: title, dtype: bool

In [150]:
str_pattern = s.str.startswith("S")
str_pattern

0    False
1     True
2     None
3    False
Name: title, dtype: object

In [151]:
str_pattern = s.str.endswith("k")
str_pattern

0    False
1    False
2     None
3     True
Name: title, dtype: object

In [152]:
starts_with_oneplus = s.str.match(r"OnePlus")
print(starts_with_oneplus)

0    False
1    False
2     None
3     True
Name: title, dtype: object

In [153]:
full_match = s.str.fullmatch(r".*256GB.*")
print(full_match)

0     True
1    False
2     None
3     True
Name: title, dtype: object

In [154]:
replaced = s.str.replace("GB", " Gigabytes", regex=False)
print(replaced)

0              Apple iPhone 15 Pro 256 Gigabytes
1         SAMSUNG Galaxy-S24 Ultra (512 Gigabytes)
2                                             None
3    OnePlus 12 12 Gigabytes/256 Gigabytes - Black
Name: title, dtype: object

Split strings into lists

Splits each string by whitespace into components. (str.split() returns lists.)

In [155]:
splits = s.str.split()
print(splits)

0          [Apple, iPhone, 15, Pro, 256GB]
1    [SAMSUNG, Galaxy-S24, Ultra, (512GB)]
2                                     None
3      [OnePlus, 12, 12GB/256GB, -, Black]
Name: title, dtype: object

Extract parts of matches
Extracts the size like "256GB" using regex groups.

In [156]:
sizes = s.str.extract(r"(\d+GB)")
print(sizes)

       0
0  256GB
1  512GB
2    NaN
3   12GB

Remove special characters

In [157]:
no_symbols = s.str.replace(r"[^\w\s]", "", regex=True)
print(no_symbols)

0      Apple iPhone 15 Pro 256GB
1    SAMSUNG GalaxyS24 Ultra 512GB
2                             None
3      OnePlus 12 12GB256GB  Black
Name: title, dtype: object

| Method                   | What it does                          |
| ------------------------ | ------------------------------------- |
| `str.contains(pat)`      | Checks if pattern in string (boolean) |
| `str.match(pat)`         | Regex match at start (boolean)        |
| `str.fullmatch(pat)`     | Exact regex match of whole string     |
| `str.replace(pat, repl)` | Replace substrings                    |
| `str.split()`            | Split string into list                |
| `str.strip()`            | Remove leading/trailing whitespace    |
| `str.lower()/upper()`    | Case conversion                       |

In [158]:
clean = (s
  .str.strip()
  .str.replace(r"\s+", " ", regex=True)
  .str.replace("-", " ")
  .str.removeprefix("SAMSUNG ")
)
clean

0        Apple iPhone 15 Pro 256GB
1         Galaxy S24 Ultra (512GB)
2                             None
3    OnePlus 12 12GB/256GB   Black
Name: title, dtype: object

Need Unicode normalization?

In [159]:
import unicodedata
s_normalized = s.map(lambda x: unicodedata.normalize("NFKD", x) if pd.notna(x) else x)
s_normalized

0         Apple iPhone 15 Pro 256GB
1    SAMSUNG Galaxy-S24 Ultra (512GB)
2                                None
3       OnePlus 12 12GB/256GB - Black
Name: title, dtype: object

Extract Information with Regex
str.extract() for first match, str.extractall() for all matches.

In [160]:
specs = s.str.extract(r"(?P<ram>\d+)\s*GB\/(?P<storage>\d+)\s*GB")
specs

   ram storage
0  NaN     NaN
1  NaN     NaN
2  NaN     NaN
3   12     256

In [161]:
idx_storage = s.str.rfind("GB")
idx_storage

0    25.0
1    29.0
2     NaN
3    19.0
Name: title, dtype: float64

Extract brand, model, storage:

In [162]:
ext = s.str.extract(r"^(?P<brand>\w+)\s+(?P<model>[\w\-]+).*?(?P<storage>\d+)GB")
ext

     brand       model storage
0      NaN         NaN     NaN
1  SAMSUNG  Galaxy-S24     512
2      NaN         NaN     NaN
3  OnePlus          12      12

 One-hot from pipe-delimited tags:

In [163]:
exp = pd.Series(["red|sale", "sale|green"]).str.get_dummies("|")
exp

   green  red  sale
0      0    1     1
1      1    0     1

In [164]:
clean = (s
  .str.strip()
  .str.replace(r"\s+", " ", regex=True)
  .str.replace("-", " ")
  .str.title()
)
clean

0           Apple Iphone 15 Pro 256Gb
1    Samsung Galaxy S24 Ultra (512Gb)
2                                None
3       Oneplus 12 12Gb/256Gb   Black
Name: title, dtype: object

In [165]:
gb_values = clean.str.extract(r'(\d+Gb)')
print("GB values found:")
print(gb_values)

GB values found:
       0
0  256Gb
1  512Gb
2    NaN
3   12Gb

In [166]:
gb_all = clean.str.findall(r'\d+Gb')
print("All GB values in each string:")
print(gb_all)

All GB values in each string:
0          [256Gb]
1          [512Gb]
2             None
3    [12Gb, 256Gb]
Name: title, dtype: object

In [167]:
# Match letters and spaces before any numbers/GB
names_only = clean.str.extract(r'^([A-Za-z\s\-]+)')[0].str.strip()
print(names_only)

0        Apple Iphone
1    Samsung Galaxy S
2                 NaN
3             Oneplus
Name: 0, dtype: object

In [168]:
import re

# Function to remove digits and GB
def extract_name(text):
    if pd.isna(text):
        return None
    # Remove numbers + GB + symbols
    text = re.sub(r'[\d/]+Gb', '', text)   # remove "256GB" etc
    text = re.sub(r'[^A-Za-z\s\-]', '', text) # remove symbols
    return text.strip()

names_only = clean.apply(extract_name)
print(names_only)

0         Apple Iphone  Pro
1    Samsung Galaxy S Ultra
2                      None
3         Oneplus     Black
Name: title, dtype: object

| Task                  | Pandas Method / Regex              |
| --------------------- | ---------------------------------- |
| Remove numbers        | `str.replace(r'\d+', '')`          |
| Remove GB             | `str.replace(r'\d+GB', '')`        |
| Remove symbols        | `str.replace(r'[^A-Za-z\s]', '')`  |
| Extract first letters | `str.extract(r'^([A-Za-z\s\-]+)')` |
| Apply custom function | `Series.apply(func)`               |

Create a clean table with title "Brand", "Model", "Storage"

In [169]:
colors = ["Black", "White", "Blue", "Red", "Green", "Silver", "Gold"]
color_pattern = "|".join(colors)

In [170]:
def extract_info(title):
    if pd.isna(title):
        return pd.Series([None, None, None])  # brand, model, storage
    
    # Extract brand (first word)
    brand = re.match(r'^[A-Za-z]+', title)
    brand = brand.group(0) if brand else None
    
    # Extract storage (number followed by GB)
    storage_matches = re.findall(r'\d+Gb', title)
    storage = storage_matches[-1] if storage_matches else None  # take last if multiple
    
    # Extract model (everything between brand and storage)
    if brand and storage:
        # Remove brand and storage from title
        model = title
        model = re.sub(r'^' + re.escape(brand) + r'\s*', '', model)  # remove brand
        model = re.sub(re.escape(storage), '', model)  # remove storage
        model = re.sub(r'\d+Gb/?', '', model)
        model = re.sub(color_pattern, '', model, flags=re.IGNORECASE)
        model = model.strip(" -")  # clean leftover dash or spaces
        model = model.replace('()', '')
        model = model.strip()
    else:
        model = None
    
    return pd.Series([brand, model, storage])

In [171]:
df = clean.apply(extract_info)
df.columns = ["Brand", "Model", "Storage"]
print(df)

     Brand             Model Storage
0    Apple     Iphone 15 Pro   256Gb
1  Samsung  Galaxy S24 Ultra   512Gb
2     None              None    None
3  Oneplus                12   256Gb